/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.sql.*;
import javax.swing.JOptionPane;
import Clases.ConsultaFacturas;

public class frmFacturas extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarFacturas
     */
    public frmFacturas() {
        initComponents();
    }
        ConsultaFacturas acc = new ConsultaFacturas();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtCliente = new javax.swing.JFormattedTextField();
        txtArticulo = new javax.swing.JFormattedTextField();
        txtEmpleado = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel2.setText("ID-Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel3.setText("ID-Empleado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 110, -1));

        jLabel5.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel5.setText("ID-Producto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel6.setText("Cantidad");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 69, -1));

        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 140, -1));

        jLabel7.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel7.setText("Precio");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 69, -1));

        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 140, -1));

        jLabel10.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel10.setText("Tipo Pago");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 80, 20));

        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 140, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 150, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 150, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 102));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Cerrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 150, -1));

        try {
            txtCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("A-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCliente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 140, -1));

        try {
            txtArticulo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("A-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtArticulo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 140, -1));

        try {
            txtEmpleado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("A-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtEmpleado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 140, -1));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 620, 120));

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registros (Todos)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 170, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("FACTURAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/erase.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/modify.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_37110.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/anterior.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/next.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String db="jdbc:ucanaccess://"+"C:/proyecto/VentaRepuestos.accdb";
            Connection cn=DriverManager.getConnection(db, "", "");
            Statement s=cn.createStatement();

            String id_Facturas=txtFactura.getText();
            String id_Clientes=txtCliente.getText();
            String id_Empleado=txtEmpleado.getText();
            String id_Servicio=txtServicio.getText();
            String Articulo=txtArticulo.getText();
            int Cantidad=Integer.parseInt(txtCantidad.getText());
            int Precio=Integer.parseInt(txtPrecio.getText());
            int suma = Cantidad * Precio;
            txtTotal.setText(""+suma);
            int Total=Integer.parseInt(txtTotal.getText());
            s.execute("insert into FacturaArticulos values('"+Articulo+"','"+id_Clientes+"','"+id_Empleado+"','"+id_Servicio+"','"
                +Cantidad+"','"+Precio+"','"+Total+"','"+id_Facturas+"')");
            JOptionPane.showMessageDialog(rootPane, "Datos Guardados");

            acc.Buscar(tblDatos);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"El error es "+ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtFactura.setText(null);
        txtCliente.setText(null);
        txtEmpleado.setText(null);
        txtPrecio.setText(null);
        txtCantidad.setText(null);
        txtArticulo.setText(null);
        txtServicio.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int resp=JOptionPane.showConfirmDialog(this,"¿Desea Cerrar?","Salir",JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if(resp==0){this.dispose();}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        acc.Buscar(tblDatos);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int fila = tblDatos.getSelectedRow();
        if (fila >= 0){

            String codigo = String.valueOf(tblDatos.getValueAt(fila, 0));
            acc.deletePersona(codigo);
            acc.Buscar(tblDatos);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        int FilaSelec =  tblDatos.getSelectedRow();
        if (FilaSelec>=0){
            txtFactura.setText(tblDatos.getValueAt(FilaSelec, 0).toString());
            txtCliente.setText(tblDatos.getValueAt(FilaSelec, 1).toString());
            txtEmpleado.setText(tblDatos.getValueAt(FilaSelec, 2).toString());
            txtServicio.setText(tblDatos.getValueAt(FilaSelec,3).toString());
            txtArticulo.setText(tblDatos.getValueAt(FilaSelec,4).toString());
            txtCantidad.setText(tblDatos.getValueAt(FilaSelec,5).toString());
            txtPrecio.setText(tblDatos.getValueAt(FilaSelec, 6).toString());
            String codigo = String.valueOf(tblDatos.getValueAt(FilaSelec, 0));
            acc.deletePersona(codigo);
            acc.Buscar(tblDatos);
        
        }else{
            JOptionPane.showMessageDialog(this,"Fila NO Seleccionada","Row Defaul Error",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String db="jdbc:ucanaccess://"+"C:/proyecto/VentaRepuestos.accdb";
            Connection cn=DriverManager.getConnection(db, "", "");
            Statement s=cn.createStatement();

            String id_Facturas=txtFactura.getText();
            String id_Clientes=txtCliente.getText();
            String id_Empleado=txtEmpleado.getText();
            String id_Servicio=txtServicio.getText();
            String Articulo=txtArticulo.getText();
            int Cantidad=Integer.parseInt(txtCantidad.getText());
            int Precio=Integer.parseInt(txtPrecio.getText());
            int suma = Cantidad * Precio;
            txtTotal.setText(""+suma);
            int Total=Integer.parseInt(txtTotal.getText());
            s.execute("insert into FacturaArticulos values('"+Articulo+"','"+id_Clientes+"','"+id_Empleado+"','"+id_Servicio+"','"
                +Cantidad+"','"+Precio+"','"+Total+"','"+id_Facturas+"')");
            JOptionPane.showMessageDialog(rootPane, "Datos Modificados Correctamente");

            acc.Buscar(tblDatos);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"El error es "+ex);
        }
        txtFactura.setText(null);
        txtCliente.setText(null);
        txtEmpleado.setText(null);
        txtPrecio.setText(null);
        txtCantidad.setText(null);
        txtArticulo.setText(null);
        txtServicio.setText(null);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int fila1= tblDatos.getSelectedRow();
        fila1=fila1-1;
        tblDatos.setRowSelectionInterval(fila1, fila1);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int fila1= tblDatos.getSelectedRow();
        fila1=fila1+1;
        tblDatos.setRowSelectionInterval(fila1, fila1);
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    private javax.swing.JFormattedTextField txtArticulo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JFormattedTextField txtCliente;
    private javax.swing.JFormattedTextField txtEmpleado;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
