/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author Gouri
 */
public class Log_in extends javax.swing.JFrame {

    int cont;
    public Log_in() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusu = new javax.swing.JTextField();
        txtContra = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Ingresar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/User-icon.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 320, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 330, 170, -1));

        txtusu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusuFocusGained(evt);
            }
        });
        txtusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuActionPerformed(evt);
            }
        });
        getContentPane().add(txtusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 180, -1));

        txtContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraKeyPressed(evt);
            }
        });
        getContentPane().add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Contraseña");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 180, -1));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ingresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Ingresar.setText("INGRESAR");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        jPanel1.add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 160, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
       this.dispose();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtusuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusuFocusGained

    }//GEN-LAST:event_txtusuFocusGained

    private void txtusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
//        consultas acc = new consultas();
//        
//         if (acc.verificar(this.txtusu.getText(),this.txtContra.getText(),this.cboUsuario.getSelectedItem().toString())){
//             
//             JOptionPane.showMessageDialog(rootPane,"Has Ingresado al Sistema como "+this.cboUsuario.getSelectedItem().toString(),
//                     "Welcome",JOptionPane.INFORMATION_MESSAGE);
//             
//             
//             Menu abrir= new Menu();
//            
//             if("Administrador".equals(cboUsuario.getSelectedItem().toString())){
//                abrir.Admin();
//                abrir.setVisible(true);
//                this.dispose();
//             }else if("Empleado".equals(cboUsuario.getSelectedItem().toString())){
//                abrir.Empleado();
//                abrir.setVisible(true);
//                this.dispose();
//             }else if("Cliente".equals(cboUsuario.getSelectedItem().toString())){
//                abrir.Cliente();
//                abrir.setVisible(true);
//                this.dispose(); 
//             }
//                              
//         }else{
//             JOptionPane.showMessageDialog(rootPane, "No se pudo acceder al Sistema \nUsuario o Contraseña Incorrecta","Sistema",JOptionPane.WARNING_MESSAGE);
//             cont ++;
//         }
//         if(cont==3){
//             JOptionPane.showMessageDialog(rootPane,"Ha sobrepasado el Limite de Entrada","Limite Excedido",JOptionPane.ERROR_MESSAGE);
//             System.exit(0);
//         }
    }//GEN-LAST:event_IngresarActionPerformed

    private void txtContraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraKeyPressed
       /* consultas acc = new consultas();
         if (acc.verificar(this.txtusu.getText(),this.txtContra.getText(),this.cboUsuario.getSelectedItem().toString())){
             
             JOptionPane.showMessageDialog(rootPane,"Has Ingresado al Sistema como "+this.cboUsuario.getSelectedItem().toString(),
                     "Welcome",JOptionPane.INFORMATION_MESSAGE);
             
             
             Menu abrir= new Menu();
            
             if ("Administrador".equals(cboUsuario.getSelectedItem().toString())){
                abrir.Admin();
                abrir.setVisible(true);
                this.dispose();
             }else if("Empleado".equals(cboUsuario.getSelectedItem().toString())){
                abrir.Empleado();
                abrir.setVisible(true);
                this.dispose();
             }else if("Cliente".equals(cboUsuario.getSelectedItem().toString())){
                 abrir.Cliente();
                abrir.setVisible(true);
                this.dispose(); 
             }
                              
         }else{
             JOptionPane.showMessageDialog(rootPane, "No se pudo acceder al Sistema \nUsuario o Contraseña Incorrecta","Sistema",JOptionPane.WARNING_MESSAGE);
             cont ++;
         }
         if(cont==3){
             JOptionPane.showMessageDialog(rootPane,"Ha sobrepasado el Limite de Entrada","Limite Excedido",JOptionPane.ERROR_MESSAGE);
             System.exit(0);
         }    */
    }//GEN-LAST:event_txtContraKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingresar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtusu;
    // End of variables declaration//GEN-END:variables
}
