/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.Informes_y_usuarios;

import Clases.Queries_Reportes;

/**
 *
 * @author gouripc
 */
public class opcionesInformes extends javax.swing.JInternalFrame {

    /**
     * Creates new form opcionesInformes
     */
    public opcionesInformes() {
        initComponents();
    }
    Queries_Reportes consultas = new Queries_Reportes();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReporte3 = new javax.swing.JButton();
        btnReporte4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnReporte2 = new javax.swing.JButton();
        btnReporte1 = new javax.swing.JButton();
        btnReporte6 = new javax.swing.JButton();
        btnReporte5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReporte3.setBackground(new java.awt.Color(0, 0, 153));
        btnReporte3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReporte3.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte3.setText("Ganancias de hoy");
        btnReporte3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporte3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporte3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 250, -1));

        btnReporte4.setBackground(new java.awt.Color(0, 0, 153));
        btnReporte4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReporte4.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte4.setText("Ganancias Mensuales");
        btnReporte4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporte4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporte4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 250, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Seleccionar Informes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        btnReporte2.setBackground(new java.awt.Color(0, 0, 153));
        btnReporte2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReporte2.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte2.setText("Producto mas vendido");
        btnReporte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporte2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 250, -1));

        btnReporte1.setBackground(new java.awt.Color(0, 0, 153));
        btnReporte1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReporte1.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte1.setText("Productos vendidos por mes");
        btnReporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporte1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 250, -1));

        btnReporte6.setBackground(new java.awt.Color(0, 0, 153));
        btnReporte6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReporte6.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte6.setText("Cant. Clientes al mes");
        btnReporte6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporte6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporte6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 250, -1));

        btnReporte5.setBackground(new java.awt.Color(0, 0, 153));
        btnReporte5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReporte5.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte5.setText("Cant. Clientes de Hoy");
        btnReporte5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporte5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporte5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 250, -1));

        tblDatos.setBorder(new javax.swing.border.MatteBorder(null));
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 810, 160));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/anterior.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/next.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporte3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte3ActionPerformed
        // TODO add your handling code here:
        consultas.totalVendidoHoy(tblDatos);
    }//GEN-LAST:event_btnReporte3ActionPerformed

    private void btnReporte4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte4ActionPerformed
        consultas.totalVendidoMesual(tblDatos);
    }//GEN-LAST:event_btnReporte4ActionPerformed

    private void btnReporte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte2ActionPerformed
        // TODO add your handling code here:
        consultas.masVendido(tblDatos);
    }//GEN-LAST:event_btnReporte2ActionPerformed

    private void btnReporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte1ActionPerformed
        // TODO add your handling code here:
        consultas.productosPorMes(tblDatos);
    }//GEN-LAST:event_btnReporte1ActionPerformed

    private void btnReporte6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporte6ActionPerformed

    private void btnReporte5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporte5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int fila1= tblDatos.getSelectedRow();
        fila1=fila1-1;
        tblDatos.setRowSelectionInterval(fila1, fila1);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int fila1= tblDatos.getSelectedRow();
        fila1=fila1+1;
        tblDatos.setRowSelectionInterval(fila1, fila1);
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporte1;
    private javax.swing.JButton btnReporte2;
    private javax.swing.JButton btnReporte3;
    private javax.swing.JButton btnReporte4;
    private javax.swing.JButton btnReporte5;
    private javax.swing.JButton btnReporte6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
